import React from 'react';
import type { Metadata } from 'next';
import HomeLinksHeader from "@/components/header/HomeLinksHeader";

export const metadata: Metadata = {
    title: {
        default: "homelinks",
        template: `%s | homelink`,

    },
    description: "Generated by www.masterconnect.ca,Free Blog Creation for you. It provides templates that the user can use to become an effective blogger.This houses the blogger's personalize homelinks.",
    keywords: ["The Blog Room, personalize homelinks", "dashboard", "bloggers", "free blog & posts", "custom page", " Show Your Own Blog", "Gary's Blogs"],

    // colorScheme:"light",

    openGraph: {
        title: "Blog.R-homelinks",
        description: 'free advance blog-set-up for a starter',
        url: "https://www.garymasterconnect.com",
        siteName: "The Blog Room -Dashboard",
        images: [
            {
                url: "/images/gb_logo.png",
                width: 600,
                height: 600
            },

        ],

    },


}

export default function UserHomeLinksLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div>
            <HomeLinksHeader />
            {children}
        </div>
    )
}
