import React from 'react';
import type { Metadata } from 'next';
import MakeAPost from "@component/header/MakeAPost";

export const metadata: Metadata = {
    title: {
        default: "Make a Post",
        template: `%s | Make posts`,

    },
    description: "Generated by www.masterconnect.ca,Free Blog Creation for you.This page allows the user to post a message.",
    keywords: ["The Post Room, personalize FREE posts", "Make A Post", "POSTS for bloggers", "free blog & posts", "Post A Message", " Create Your Own POST", "Gary's Blogs"],

    // colorScheme:"light",

    openGraph: {
        title: "Post Room",
        description: 'View free posts from important bloggers',
        url: "https://www.garymasterconnect.com",
        siteName: "The Blog Room - Post Room",
        images: [
            {
                url: "/images/gb_logo.png",
                width: 600,
                height: 600
            },

        ],

    },


}
export default function BlogLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div>
            <MakeAPost />
            {children}
        </div>
    )
}
